### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by ivklgn** [Sahar12j14/Website#1]
Имя репозитория названо с ошибкой (англ. язык)

**Comment by ivklgn** [comment]
настройте prettier, форматирование в html убито

**Comment by ivklgn** [comment]
проверьте код w3c валидатором

**Comment by ivklgn** [comment]
имена файлов не должны содержать пробелы. - используйте разделители

**Comment by ivklgn** [comment]
имена папок с css и картинками приведите в порядок 
https://github.com/lulldev/webdev/blob/master/coding-convections/project-structure.md

**Comment by ivklgn** [comment]
```css
body {
  background-color: #292727;
  color: #e0d3d3;
}
rectangle {
  box-shadow: 0px 2px 0px rgba(255, 255, 255, 0.16);
}
line {
  border: 2px solid #e0d3d3;
}
line3 {
  border: 2px solid #e0d3d3;
}
```

мы не стилизуем теги - используйте классы
